spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
      use-new-id-generator-mappings: true
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin@power.oj
server:
  error:
    include-stacktrace: never
